global:
  scrape_interval: 15s # 15초마다 수집

scrape_configs:
  # 1. Main Backend (only4_be) 감시
  - job_name: 'only4-be'
    metrics_path: '/actuator/prometheus'
    static_configs:
      # host.docker.internal = 도커 안에서 내 컴퓨터(Localhost)를 찾는 주소
      # 나중에 실제 주소로 변경
      - targets: ['host.docker.internal:8080']

  # 2. Kafka Consumer (only4_kafka) 감시
  - job_name: 'only4-kafka'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8081']

  # 3. Kafka Broker 자체 감시
  - job_name: 'kafka-broker'
    static_configs:
      # 도커 내부끼리 통신하므로 서비스명 사용
      - targets: ['kafka-exporter:9308']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']