spring:
  profiles:
    # local : IntelliJ에서 개발할 때
    # dev   : Docker Compose로 실행할 때
    # prod  : 실제 배포할 때
    active: local

  # 공통 설정
  application:
    name: only4-be

  datasource:
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

        # 1. 읽기 최적화 (Bulk Fetch) - Reader 성능 향상
        default_batch_fetch_size: 1000

        # 2. 쓰기 최적화 (Bulk Insert) - Writer 성능 향상
        jdbc:
          batch_size: 1000        # INSERT를 1000개씩 묶음
          order_inserts: true     # 같은 INSERT끼리 정렬해서 묶음 효과 극대화
          order_updates: true     # UPDATE도 정렬

  # 스프링 배치 필수 설정
  batch:
    jdbc:
      initialize-schema: always # 배치 실행에 필요한 메타 테이블(BATCH_JOB_INSTANCE 등)을 자동 생성
    job:
      enabled: false  # 앱 실행될 때 모든 배치가 자동 실행되는 것 방지 (보통 막아둠)

  kafka:
    bootstrap-servers: localhost:9092
    topic:
      notification: email.send.request
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
  #     value-serializer: org.apache.kafka.common.serialization.StringSerializer #String
        # DTO 객체를 보내기 때문에 Json 직렬화가 필요함
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      linger-ms: 10         # 메시지가 적어도 10ms는 기다렸다가 모아서 보냄
      delivery.timeout.ms: 30000



# ==========================================
# [커스텀 앱 설정]
# ==========================================
app:
  kafka:
    topics:
      group-id: only4-consumer-group
      email-request: email.send.request

    retry: # 재시도 관련 설정
      email-max-attempts: 3
      initial-interval-ms: 500 # 재시도 간격의 시작값 / 0.5초 후 첫 재시도
      max-interval-ms: 30000 # 재시도 간격 상한 / 아무리 커져도 30초를 넘지 않음

# ==========================================
# [모니터링 & 액추에이터 설정]
# ==========================================
management:
  # 1. 엔드포인트 노출
  endpoints:
    web:
      exposure:
        include: prometheus, health, info, metrics, loggers, threaddump, heapdump

  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always

  # 메트릭 상세 설정
  metrics:
    tags:
      application: ${spring.application.name} # 태그 부착

    # API 응답 속도(Latency) 분포 수집
    distribution:
      percentiles-histogram:
        http.server.requests: true
      sla:
        http.server.requests: 100ms, 500ms, 1s # 1초 넘는 요청 카운팅

    enable:
      jvm: true
      process: true
      system: true
      hikaricp: true # DB 커넥션 풀 모니터링
      jdbc: true
      kafka: true # Kafka 메트릭 수집
      logback: true # Error 로그 발생 횟수 카운트
